services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /app
    
    volumes:
      - .:/app
    
    networks:
      - laravel_network

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    
    ports:
      - "80:80"
    
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    
    depends_on:
      - app
    
    networks:
      - laravel_network

  mysql:
    image: mysql:8.0.39
    container_name: laravel_mysql
    restart: unless-stopped
    
    volumes:
      - mysql_data:/var/lib/mysql
    
    networks:
      - laravel_network

  redis:
    image: redis:7.4-alpine
    container_name: laravel_redis
    restart: unless-stopped
    
    networks:
      - laravel_network

volumes:
  mysql_data:

networks:
  laravel_network:
    driver: bridge